git_user_name:
git_user_email:

timezone: "Asia/Singapore"

# NOTE: You can hide values using ansible-vault (see below or in ansible/README.md)
#
# ------- Encrypt values --------
# [SSH Private Key]: cat <SSH_PRIV_KEY_FILE> | ansible-vault encrypt_string --vault-password-file <PATH_TO_PASSWORD_FILE> --stdin-name "id_ed25519"
# [SSH Private Key]: cat <SSH_PRIV_KEY_FILE> | ansible-vault encrypt_string --vault-password-file <PATH_TO_PASSWORD_FILE> --stdin-name "id_ed25519"
ssh_keys:
# id_ed25519: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   643034363562383163633030636630633 ...
# id_ed25519.pub: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   643034363562383163633030636630633 ...

# machine_os: "debian" # Supported: "debian", "redhat", "archlinux"
python_version: "3.12"
